### ISSUE TITLE
Discovery and Questions about Project for New Members

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#320]
### Issue Description

In the first meeting's actions decision part the team has decided to create an issue for the new members to understand the project structure, this is a discovery issue that will be fulfilled by @gokayyildiz and me @Koraytkn. 

### Step Details

Steps that will be performed:
- [x] Discovery of Scenarios & Mockups
- [x] Discovery of Diagrams
- [x] Discovery of Requirements
- [x] Discovery of Practice App Documentation

### Final Actions

During and after the discovery process the subjects of this issue (new members) will be asking questions to old members about the project structure, the aim is to have each member aware of the current status of the project. 

### Responsible People

- [x] Koray Tekin
- [x] Mehmet Gökay Yıldız

### Deadline of the Issue

10.10.2022 - 23.59

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

11.10.2022 - 23.59

### Final To-Dos

- [ ] Each question has been answered and the confusion resolved properly.

**Comment by Koraytkn** [comment]
@xltvy Altay while I was looking at the use case diagram I couldn't understand one part clearly. I wanted to ask, do you remember what does the "create event" use case supposed to represent; as far as I see it extends the "chat" use case but why is the subject specified as "lecturer" when the "chat" case is included in the "viewing home page" which is a use case for a registered user? Thanks in advance.

**Comment by Koraytkn** [comment]
@onurkomurcu  Onur Hi, I was going over the practice app non-functional requirements part and I wanted to ask what "...should not contain a confusing linking system" means under the usability title. Thanks in advance.

**Comment by xltvy** [comment]
> @xltvy Altay while I was looking at the [use case diagram](https://github.com/bounswe/bounswe2022group2/wiki/Use-Case-Diagram) I couldn't understand one part clearly. I wanted to ask, do you remember what does the "create event" use case supposed to represent; as far as I see it extends the "chat" use case but why is the subject specified as "lecturer" when the "chat" case is included in the "viewing home page" which is a use case for a registered user? Thanks in advance.

In our use-case diagram, actors are illustrated as human like symbols. Since we do not officially differentiate users about whether they are lecturer or learner, we have only 3 types of users (actors): registered, unregistered users, and admin. A registered user is also a learner and a lecturer at the same time. So, when we see (lecturer) above any arrow, it means that this feature is for the users who are a lecturer of a lecture only or vice versa when it is (learner).

Regarding the chat feature, in our requirements specification _"1.2.5.3. The chat should include the feature of creating events."_ it is said that an event can be created through chat. The diagram says that a user can create an event of a lecture when they are a lecturer of that lecture.

Regarding the home page part, I think there is ambiguity about creating an event for our project regarding your question. Because I don't think there is any requirements specification about having the chat in the homepage. We have even said that _"1.2.5.1. The chat features should be unique to the lecture. There is no common channel for the entire community."_ So, there is not any chat feature in the main page. Thus, I think we need to update the use-case diagram regarding this ambiguity. 

As a side note, I think we can completely wipe out creating an event from the chat idea completely, since doing it in the chat window would be harder and more complex to implement compared to making it a standalone feature/part in the lecture page. I will move this discussion in the requirements revision issue #323 and we can discuss it further. But so far, my explanation above holds I believe. If there is anything that you did not understand I can explain it further.

**Comment by gokayyildiz** [comment]
Questions that come to my mind after the review of the repository were answered both in ps meetings and weekly team meetings

**Comment by onurkomurcu** [comment]
> @onurkomurcu Onur Hi, I was going over the practice app [non-functional requirements](https://github.com/bounswe/bounswe2022group2/wiki/Practice-App-Requirements) part and I wanted to ask what "...should not contain a confusing linking system" means under the usability title. Thanks in advance.

- "2.1.1 The system should provide a user-friendly interface. It should contain a basic site map and should not contain a confusing linking system."

Actually, the part that you ask is explained in the first part of the requirement. For instance, if user want to search course, it should be in the home page. These kind of crucial actions should be accessed easily in the site. This requirement refers to this. 

If you have any further questions regarding to our project @gokayyildiz and @Koraytkn, feel free to reopen this issue or ask them in our weekly meetings. Thank you for your great effort to adapt to our project!
