### ISSUE TITLE
Research & Report for Backend Technologies (Backend Team)

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#321]
### Issue Description

After our first meeting, backend team for our project has been decided as @codingAku, @mbatuhancelik and @hasancan-code. Our first task as backend team is make a research and present our findings about various technologies for implementing backend, first ideas include Node & Python FastAPI.

### Step Details

Steps that will be performed:
- Find pros and cons of various technologies and their performance/complexity
- Present your findings
- Decide on the most optimal solution

### Final Actions

After our research is complete and the technology we should use is decided, we will connect with our Mobile and Frontend team and let everyone in the group know about it.

### Responsible People

- [x] Mehmet Batuhan Çelik
- [ ] Hasan Can Erol
- [x] Ecenur Sezer

### Deadline of the Issue

10.10.2022 - 23:59

### Final To-Dos

- [X] Every responsible shared an info about the sections/parts s/he will perform.
- [ ] Every responsible mentioned the sub-issue contains the details of his/her work, if a sub-issue is created.
- [ ] Every responsible mentioned this issue in the description of his/her sub-issue, if a sub-issue is created.

**Comment by codingAku** [comment]
Node vs. FastAPI

I have put the features I believe most significant in order from top to bottom. After my findings, I believe for our student project, a widely used technology with asyncronous programming like Node.js would be compatible for our backend development.

FastAPI findings:

- FastAPI is properly fast when we compare it to other major Python frameworks like Flask and Django.

- The most exciting feature of FastAPI is that it supports asynchronous code out of the box using the async/await Python keywords.

- Testing FastAPI endpoints are really straight forward and can be done using TestClient provided by FastAPI. This could be useful.

- FastAPI has a very extensive and example rich documentation, which makes things easier. If you need to look up something about FastAPI, you usually don't have to look elsewhere.

- You can easily deploy your FastAPI app via Docker using FastAPI provided docker image.

Node.js findings:

- According to Node.JS’s 2016 User Survey, JavaScript is one of the most well-liked programming languages for front-end development, with almost 85% preferring it over other alternatives like Python or Ruby.

- Node.js also enjoys the support of a large and active community, which is always willing to help out with any queries or problems that you might face.

- It is a globally-used technology that has attracted millions of developers to work on it and solve even the most complicated problems across different industries, including tech giants like Google or Microsoft.

- Thus, it has the support of a large and active community which proves to be one of the significant advantages of node.js.

- Node.js has a built-in package manager named NPM, which comes with the language. This is made for installing different packages that are available on the internet on Node.js servers easily and quickly.

- One of the most significant disadvantages of node.js is that its APIs are not stable. Since Node.js does not provide stable APIs, developers face certain difficulties while writing the programs that require stable APIs.

**Comment by mbatuhancelik** [comment]
Here are some options from me with their pros and cons, mostly based on my development experience and discussions with @codingAku :

Fast API: 
As its still not out of the alpha versions yet, FastAPI packs important features like authorization, automated documentation, request validation and some middleware options. It is designed to get a lightweight api working as soon as possible, thus, promises a decrease in development time. Since it is very python-like, it is easy to learn. On top of that, it is served on uvicorn, one of the most resource-efficient web server implementations,  leaving us plenty of space on the server for the frontend. Backsides is that it cannot host web pages or sockets, thus we will be needing another server to host our website and chat functionality. It is still new in the environment, so a lack of recognition and userbase support and some unexpected bugs are expected.

Django: 
Even though it is the most popular in the python environment with lots off capabilities like serving files, out of box security and mongo connection, It has a very unique way to code. I believe we wont be using utilizing most of those properties so it may not worth the suffer the learning process. 

Node:
With a plethora of userbase support, there is nothing we are to do thats not done on Node and most of those stuff are served as packages for us to use. On the other hand horrific design of JS might hurt us(me) a little bit.

Java w/ Spring: 
Like node, java comes with great package/userbase support(even though not so great as node). Using a statically typed language might help us reduce bugs. On top of that it comes with really good parallelism support. Its learning curve is not as steep as js but not as flat as python. The real problem is its RAM usage, we might need multiple EC2 instances(assuming we are using free ones) to get our API running.

**Comment by codingAku** [comment]
The technologies for backend are already set, so no need to keep this issue open.
