### ISSUE TITLE
Revisions About All the Diagrams 

### ISSUE THREAD

**Issue by hasancan-code** [bounswe/bounswe2022group2#322]
### Issue Description

As we talk in our first meeting for this semester, we have to revise [Use Case Diagram](https://github.com/bounswe/bounswe2022group2/wiki/Use-Case-Diagram), [Class Diagram](https://github.com/bounswe/bounswe2022group2/wiki/Class-Diagram) and [Sequence Diagram](https://github.com/bounswe/bounswe2022group2/wiki/Sequence-Diagram) and decide the final shape of the diagrams. After that creation of the app can be started. 

Every group member should check the diagrams and if he/she has anything to add or change should note under this issue.  

### Step Details

Steps that will be performed:
- Check all the diagrams
- Decide what is going to actually use or change
- Comment your ideas under this issue

### Responsible People

- [x] Bahrican Yesil
- [x] Egemen Atik
- [x] Altay Acar
- [x] Ezgi Aysel Batı
- [x] Muhammed Enes Sürmeli
- [x] Onur Kömürcü
- [x] Mehmet Batuhan Çelik
- [x] Hasan Can Erol
- [x] Ecenur Sezer
- [x] Koray Tekin
- [x] Mehmet Gökay Yıldız

### Deadline of the Issue

10.10.2022 - Monday - 23.59

### Deadline for the Review

11.10.2022 - Tuesday - 23.59

**Comment by bahricanyesil** [comment]
I analyzed the class, use-case, and sequence diagrams separately and noted the things I consider as important. You can find the conclusions of my review under:

**Comment by mbatuhancelik** [comment]
Here is my take on this one: 

- While we were designing the diagrams we had a sequential database in mind, but our using a document based database is more likely now, so the whole data model needs a revision, possibly in a design meeting. Problem here is that, our data model should be designed with DBSM in mind, different document based databases and database providers may require different design choices.
- We avoided controllers during the last semesters design as instructed by our CMPE352 TA Egemen, yet now we need them, so they should be added.
- Since we decided on using node JS, we are most likely to use a monolithic structure(this is not decided yet), however, our app now is designed in Java's OOP design. We should make our mind about which structure we will use. It even may be on the table to creating microservices for different functionality, affecting heavily our class diagram.

**Comment by codingAku** [comment]
My findings on our diagrams are:
- We need controller structures, almost on all of our classes.
- We need to change enrollment class and remove event related fields.
- I cannot see ChatBox class we mentioned in chat class.
- On Achievement and Badge and Quiz classes we may add get and set methods since they appear on different classes.
-

**Comment by surmelienes1** [comment]
Here are some points on how our diagrams could be revised:

* According to our TA, Alper, we need to delete the Chat class from the [Class Diagram](https://github.com/bounswe/bounswe2022group2/wiki/Class-Diagram) since the customer expects us to do so.

* Since we are now required to have controllers, we should incorporate them into our design of the [Sequence Diagrams](https://github.com/bounswe/bounswe2022group2/wiki/Sequence-Diagram).

* The enrollment class needs to be changed, and some list variables indicated by the TA Alper should be included keeping the relationships of the enrollment class with other classes in mind. Some unnecessary variables like poll_id and chapter_id should also be removed from the class diagram.

* Since the construction of the diagrams and how they are portrayed depends heavily on our [Requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements), we will likely need to make some further alterations on the diagrams when we conclude the requirement revisions.

* Aside from these, I agree with the suggestions provided by @bahricanyesil, @mbatuhancelik, and @codingAku and recommend that we should consider going over these suggestions to revise our diagrams at our next meetings.

**Comment by onurkomurcu** [comment]
I have revised the parts of the diagrams which are related to achievements. Details can be found under the issue #346.

**Comment by Koraytkn** [comment]
I have revised and updated the diagrams considering the related requirements change rooting from chat to discussion conversion details can be found at https://github.com/bounswe/bounswe2022group2/issues/344

**Comment by bahricanyesil** [comment]
I have revised and updated the diagrams related to signup&login (+authentication in general) functionalities. Conversion details can be found under #337.

**Comment by xltvy** [comment]
As we have discussed in our [meeting 2](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-2-for-451-(12.10.2022)), we have revised the notifications section of the requirements specification with @surmelienes1 and were also responsible for the revision of the parts of diagrams related to the notifications.

Since there is not any content related to the notifications in diagrams as we have skimmed through the diagrams, there is no need to update any diagram related to our work in notifications.

**Comment by egemenatikk** [comment]
I revised and updated the diagrams related to lecture structure functionalities. Details can be viewed under issue numbered #347

**Comment by ezgy** [comment]
I revised and updated diagrams related to user—lecture interaction (enrollment in class diagram) details can be found under issue #343
