### ISSUE TITLE
Revising Mockups 

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#326]
### Issue Description

In the last semester, we made some scenarios and mockups for our project. In this semester, before starting the coding and developing the actual project, we decided to go through the mockups. All team members are responsible for this task. If there are any suggestions or questions about mockups, it will be written under this issue.

### Step Details

Steps that will be performed:
-  Checking mockups.
-  Taking notes for feedbacks.
- Mention them under this issue.

### Final Actions

After all of the feedbacks are gathered, they will be evaluated with our TA to finalize our work.

### Responsible People

- [x] Bahrican Yesil
- [ ] Egemen Atik
- [x] Altay Acar
- [x] Ezgi Aysel Batı
- [x] Muhammed Enes Sürmeli
- [ ] Onur Kömürcü
- [x] Mehmet Batuhan Çelik
- [ ] Hasan Can Erol
- [ ] Ahmet Yiğit Özdoğan
- [ ] Ecenur Sezer
- [ ] Koray Tekin
- [ ] Mehmet Gökay Yıldız

### Deadline of the Issue

10.10.2022 - Monday - 23.59

### Reviewer

@codingAku 

### Deadline for the Review

11.10.2022 - Tuesday - 15.00

**Comment by bahricanyesil** [comment]
I looked at the mockups but I have a different perspective on this issue:

We have created previous mockups to just be an example for us and for our scenarios. They are not representing the real app that we will develop. Therefore, revising them doesn’t make sense to me. If we will implement the design of the app we will develop, then we should start mockups from scratch by designing them for both mobile and web separately also we should think about all possible screens at the 0 point and create mockups for these screens since we will use them while coding mobile app and front-end of the web app. So, I do not have any revisions right now.

**Comment by mbatuhancelik** [comment]
> I looked at the mockups but I have a different perspective on this issue:
> 
> We have created previous mockups to just be an example for us and for our scenarios. They are not representing the real app that we will develop. Therefore, revising them doesn’t make sense to me. If we will implement the design of the app we will develop, then we should start mockups from scratch by designing them for both mobile and web separately also we should think about all possible screens at the 0 point and create mockups for these screens since we will use them while coding mobile app and front-end of the web app. So, I do not have any revisions right now.

Second that, while preparing our action plan for this semester under #316 I added design meetings for the requirements that will be implemented that week. During this meeting we can discuss the final shape of the UX design.

**Comment by xltvy** [comment]
Agreed @bahricanyesil and @mbatuhancelik , we can skip revising mockups and provide final versions after UI&UX designs are finalized.

**Comment by ezgy** [comment]
I too agree that mockups shouldn't be revised, but they can be used as a basis to discuss our design for core features. Maybe we can review them together at the next meeting?

**Comment by surmelienes1** [comment]
Considering our current [Project Plan](https://www.notion.so/a65c56f90ecb4d3fb318935283751e05?v=846337c07136445b9c1bae89766b6cb2) and taking a look at our [mockups](https://github.com/bounswe/bounswe2022group2/wiki/Unregistered-Learner-Scenario,-Ai-Zheng#mockup) from the last semester, there are two points I can mention:

* Since our TA, Alper, had commented during the last lab session that we did a great job of preparing our previous designs or mock-ups, we should not make significant modifications to them.

* In addition, it would be better for us to hold off on revising the mock-ups this week so as to avoid overdoing and overloading the design part as we could need, according to our project plan, to build new designs or mock-ups in the coming months to fulfill the requirements of the frontend part of the development.

**Comment by onurkomurcu** [comment]
As we discussed in the lab session, we delayed this work. So this issue can be closed now.
