### ISSUE TITLE
Revising Glossary on Requirements page

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#43]
### Issue Description

Upon reviewing work done last week, it was decided in the team meeting that the glossary for the requirements page can be revised. The goal is to better define some words that were too generic to better fit project terminology as well as eliminate terms used for the same meaning to a single consistent word that will be used going onwards.

### Step Details

Steps that will be performed:
- [x] Merging words that have the same or very similar meaning ( ex: Educator - Lecturer)
- [x] Improving definitions to better fit project-specific terminology. 
- [x] Removing unnecessary words if there are any
- [x] Adding any new words if needed from new additions to the requirements

### Final Actions

Progress will be documented by adding a checkmark on the step details and adding any additional information via comments under this issue. As the improvements will be directly applied on the [requirements page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements), they can be reviewed by the reviewer @egemenatikk or any other member at the relevant page after the deadline.  

### Deadline of the Issue

21.03.2022 - Monday - 23.59

### Reviewer

Egemen Atik

### Deadline for the Review

22.03.2022 - Tuesday - 10.00

**Comment by ezgy** [comment]
- I have revised the glossary description of terms used in Lecture Requirements as proposed  in #39 
- Removed similar words and united under one term
- Removed some terms that were no longer used in requirements
TODO: 
- More revising descriptions to better fit use in requirements context
- Adding or removing words according to changes made to the requirements

**Comment by onurkomurcu** [comment]
I have done following updates on glossary.

* **Message**, **sender** and **timestamp** definitions are added after addition of **Chat Requirements**.
* **Sign up** and **follow** definitions are revised to be better fitting with project.
* **App** and **application** definitions are added.
* **Guest** definition is deleted since in the app there won't be any guest user.
* Punctuation missing is fixed.

If you have any suggestion, you can freely contribute to this work.

**Comment by egemenatikk** [comment]
I have reviewed the updated glossary in our requirements page. Definitions are more accurate for our project than it was before. Also, usage of words are correct. For example, we call the users who try to learn "Learners" and users who give the courses "Lecturers".  Also, I think new words that may need definitions are added. Thank you for your contribution.

I congratulate the contributors. I am closing this issue since the task is done and reviewed, but it is more than welcomed to get feedbacks from other members of our group.

**Comment by ezgy** [comment]
Glossary has been edited: many words that were used in their default meaning have been removed. Definitions have been modified to represent meaning for the platform.  Missing words have been added.
Waiting for suggestions/review from any member.

**Comment by ezgy** [comment]
Work has been approved so this issue will be closed. If you have any changes or improvements to suggest please reopen issue.
