### ISSUE TITLE
Creating Persona and Scenario with Pre-Conditions for Creating Community Events

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#50]
### Issue Description

We will be creating a persona who is a lecturer that wants to create a community event.

### Deadline of the Issue

21.03.2022 - Monday 23.59

### Reviewer

Muhammed Enes Sürmeli @surmelienes1 

### Deadline for the Review

22.03.2022 - Tuesday 23.59

**Comment by codingAku** [comment]
@ezgy and I have completed the the creating event scenario. You can access the details from [here](https://github.com/bounswe/bounswe2022group2/wiki/Lecturer-Creates-Community-Event-Scenario,-Ezgi-Ece-Smith). Review is needed by @surmelienes1.

**Comment by surmelienes1** [comment]
I went over the persona, user story, goals, pre-conditions, scenario, and acceptance criteria parts of the [Creating Event Scenario](https://github.com/bounswe/bounswe2022group2/wiki/Lecturer-Creates-Community-Event-Scenario,-Ezgi-Ece-Smith).

The example persona has well-defined personal features and storyline, and the given scenario seems to fit well with our [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements#requirements).

From my point of view, it looks pretty good and complete. Thank you [Ecenur](https://github.com/bounswe/bounswe2022group2/wiki/Ecenur-Sezer) and [Ezgi](https://github.com/bounswe/bounswe2022group2/wiki/Ezgi-Aysel-Bat%C4%B1) for your valuable contributions.

This issue will now be closed since the review procedure has been completed. If you have further questions, suggestions, or ideas you can reopen this issue and add your thoughts as a comment.
