### ISSUE TITLE
Providing mockups for Creating Community Events

### ISSUE THREAD

**Issue by hasancan-code** [bounswe/bounswe2022group2#56]
### Issue Description

As we have discussed and determined in  [meeting3](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%233-(17.03.2022)), I took the responsibility of providing mockups for the scenario of creating community events. Pre-Conditions for Community Events and the scenario is accessible in issue #50

After the initial phase of providing mockups is finished,

### Final Actions

I completed the mockups for the scenario. This issue will be closed and mockups will be added to the wiki page after reviewing the process.
You can check [figma link](https://www.figma.com/file/tpvTWyPsigFFyR5f9lYvIl/CMPE352-mockups?node-id=0%3A1). 

### Deadline of the Issue

22.03.2022 Tuesday 23:59

### Reviewer

Muhammed Enes Sürmeli

**Comment by ezgy** [comment]
I've reviewed your design on figma and have one simple suggestion: currently, the way fields are designed contains *duration* as minutes and *date* as day/month/year, which makes it so the start time of the event is unknown. Perhaps we can change the "duration" to a format similar to google calendar (17.00-18.30) or add an additional field _start:_ to enter starting time?

**Comment by surmelienes1** [comment]
As Ezgi mentioned above, an addition can be made for the start time of a created meeting so that we can eliminate the uncertainty, and an e letter is missing between the letters c and m when writing "announcements" on the last page, but it is not a big problem.

Other than that, from my point of view, I don't see any changes which needs to be made. It looks very good and complete, great job! Thank you [Hasan Can](https://github.com/bounswe/bounswe2022group2/wiki/Hasan-Can-Erol) for your valuable contributions.

If you don't have further questions, suggestions, or ideas, you can close this issue.

**Comment by hasancan-code** [comment]
Thanks for the reviews Ezgi and Enes. I made the necessary changes. You can check from figma [link](https://www.figma.com/file/tpvTWyPsigFFyR5f9lYvIl/CMPE352-mockups?node-id=59%3A233).
