### ISSUE TITLE
Determining Annotation Requirements

### ISSUE THREAD

**Issue by ahmet633** [bounswe/bounswe2022group2#68]
### Issue Description

Issue Description

I will be determining annotation requirements which will be consistent with the all requirements. All the progress can be seen from here. If you have any suggestion and question regarding this topic, feel free to contribute.

### Deadline of the Issue

27.03.2022 - Sunday 23.59

### Reviewer

Muhammed Enes Sürmeli

**Comment by ahmet633** [comment]
I created requirements about annotations. You can find them [here](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) (1.2.8.). If these requirements are found adequate, then I will add profile page requirements with points regarding annotations. Waiting for review from @surmelienes1 .

**Comment by surmelienes1** [comment]
Thank you for your efforts! I reviewed the requirements you created. You can see the parts for which I made some suggestions and have questions in my mind, listed below:

1) I think it should be written as comply with instead of comply to in the 1.2.8.2. section according to grammatical rules.

2) You can also add the "Annotations must follow the W3C standards" condition in the project description document to the requirements.

3) You could elaborate a bit on what you mean by relevant target resource(s) in the 1.2.8.4. section.

4) I think it would be enough if you wrote the items in 2 separate sections as may have zero or more body attributes and may have one or more target attributes instead of these 1.2.8.5., 1.2.8.6., and 1.2.8.7. items since they have similar meanings.

5) You wrote that annotations will be accessible when they are public in the 1.2.8.8. section, then is the first part of the 1.2.8.4. section necessary?

6) Finally, I think it would be better if you could add a few requirements about the part stated in the project description document as:

        “Users will be able to annotate content on the platform with text or images. The text may be a URI in which case it should serve as a hyperlink. These links may be to semantic resources which provide detailed information related to the resource.”

**Comment by onurkomurcu** [comment]
I think there is no need to change anything current version of the annotation requirements. So, I am closing this issue. Thank you for your work.
