### ISSUE TITLE
Software Design: Use Case Diagram - Authentication

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#72]
### Issue Description

This is a sub issue from #70. 

Use case diagram for signing up and logging in including almost done steps will be created under this issue.

These use cases shall cover 1.1.1. , and 1.2.6. from [requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements), including:

- sign in
- login
- logout
- forgetting / changing password

Diagram in [Lucichart](https://lucid.app/lucidchart/975d6056-2874-4fb9-8642-fc1a3a88aab4/edit?invitationId=inv_dfe17a81-20af-4a01-9d13-dbcc4f7ade2c).

### Final Actions

Diagrams created here must be merged with others.

### Deadline of the Issue

02.01.2022 Saturday 14.00

### Reviewer

Altay Acar

### Deadline for the Review

02.01.2022 Saturday 15.00

**Comment by mbatuhancelik** [comment]
I created a prototype at lucidchart page given in the issue.
I left a vague end for selecting courses, which will point to searching and adding courses when they are created.
Review is requested @xltvy

**Comment by mbatuhancelik** [comment]
Scope of this issue grows as I continue adding diagrams :D

**Comment by mbatuhancelik** [comment]
Now all requirements from 1.1.1. and 1.2.6. should be covered.
I guess we are ready for review! @xltvy

**Comment by xltvy** [comment]
Thank you for your comprehensive work! I have reviewed the authentication section of the use-case diagram. Here are some points I would like to mention:
* Since forgot password option is directly related to a **registered** user, I think we may not bind it to the **non-registered user**
* After **Almost Done** , the application would ask to select interest areas, not lectures as long as I remember. Correct me if I am wrong. So, I think we may replace lectures with interest areas.
* Accepting privacy policy and terms&conditions may be separated, since they are two separate subjects.
* I think there is another wording issue here: A **non-registered user** would not sign in, they would **sign up**. So, we may replace that as well.

**Comment by mbatuhancelik** [comment]
These propositions are discussed in our meeting about merging use cases.
I made the necessary changes on the diagram!

**Comment by bahricanyesil** [comment]
@mbatuhancelik, I needed to re-review the diagram you created after our group meeting. We need to add two more actions:

1. Forgot password
2. Delete account
